name: Nightly
on: [ push ]

jobs:
  buildAppxBundle:
    name: Build AppInstaller
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Prepare Env
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build AppInstaller 
      shell: pwsh
      run: |
        MSBuild broken-msbuild.csproj -nologo -r -v:diagnostic /t:Restore /p:Configuration=Release /p:RuntimeIdentifier="win-x86"
      
    - name: Build AppInstaller 
      shell: pwsh
      run: |
        MSBuild broken-msbuild.csproj -t:Build /p:Configuration=Release /p:AppxPackageSigningEnabled=True /p:UapAppxPackageBuildMode="SideloadOnly" /p:Platform=x86 /p:PackageCertificateKeyFile="broken-msbuild_TemporaryKey.pfx" /p:PackageCertificatePassword="" /p:AppxBundle=Never
      env:
#         GenerateAppInstallerFile: True
        AppInstallerUri: "https://demo.demo/"
        
    - name: Check dir 2
      shell: pwsh
      run: dir -Force
